/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

 plugins {
    application
    checkstyle
    jacoco
    id("org.openjfx.javafxplugin") version "0.0.13"
}
javafx {
    version = "17"
    modules("javafx.controls", "javafx.fxml")
}

jacoco {
    toolVersion = "0.8.9"
    reportsDirectory.set(layout.buildDirectory.dir("customJacocoReportDir"))
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(false)
        csv.required.set(false)
        html.outputLocation.set(layout.buildDirectory.dir("jacocoHtml"))
    }
}

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = "0.7".toBigDecimal()
            }
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    
    implementation("com.opencsv:opencsv:5.5")
    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    implementation("org.openjfx:javafx-controls:20.0.1")
    implementation("org.openjfx:javafx-fxml:20.0.1")
}

application {
    // Define the main class for the application.
    mainClass.set("myproject.minesweeper.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    // maxParallelForks = 1

}
